name: Apply Patch (PR)
on:
  workflow_dispatch:
    inputs:
      title:
        description: PR title
        required: true
        type: string
      body:
        description: PR body/notes
        required: false
        type: string
      diff:
        description: Unified diff (patch)
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create branch and apply diff
        run: |
          BRANCH="bot-fix-$(date +%s)"
          git checkout -b "$BRANCH"
          printf '%s' "${{ inputs.diff }}" > /tmp/patch.diff
          git apply -p0 /tmp/patch.diff
          git add -A
          git -c user.name='chatops-bot' -c user.email='bot@users.noreply.github.com' commit -m "${{ inputs.title }}"
          git push origin "$BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
      - name: Open PR
        uses: actions/github-script@v7
        with:
          script: |
            const res = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: process.env.BRANCH,
              base: "main",
              title: core.getInput("title"),
              body: core.getInput("body") || ""
            });
            core.notice(`PR: ${res.data.html_url}`);
